/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Smart Home Device API
 * API to manage and retrieve smart home devices.
 * OpenAPI spec version: 1.0.0
 */
import type {
  Configuration,
  ConfigurationListItem,
  Device,
} from "./device-api.schemas";
import { customInstance } from "./axios-instance";

export const getSmartHomeDeviceAPI = () => {
  /**
   * Retrieve a list of all registered smart home devices.
   * @summary List all devices
   */
  const getDevices = () => {
    return customInstance<Device[]>({ url: `/devices`, method: "GET" });
  };

  /**
   * Retrieve a single device by its ID.
   * @summary Get device
   */
  const getDevice = (id: string) => {
    return customInstance<Device>({ url: `/device/${id}`, method: "GET" });
  };

  /**
   * Retrieve a list of configurations for a device.
   * @summary Get device configurations
   */
  const getDeviceConfigurations = (id: string) => {
    return customInstance<ConfigurationListItem[]>({
      url: `/device/${id}/configurations`,
      method: "GET",
    });
  };

  /**
   * @summary Create device configuration
   */
  const createConfiguration = (id: string, configuration: Configuration) => {
    return customInstance<Configuration>({
      url: `/device/${id}/configurations`,
      method: "POST",
      headers: { "Content-Type": "application/json" },
      data: configuration,
    });
  };

  /**
   * Retrieve a single configuration for a device.
   * @summary Get device configuration
   */
  const getConfiguration = (id: string, configurationId: string) => {
    return customInstance<Configuration>({
      url: `/device/${id}/configuration/${configurationId}`,
      method: "GET",
    });
  };

  /**
   * Update a single configuration for a device.
   * @summary Update device configuration
   */
  const updateConfiguration = (
    id: string,
    configurationId: string,
    configuration: Configuration,
  ) => {
    return customInstance<Configuration>({
      url: `/device/${id}/configuration/${configurationId}`,
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      data: configuration,
    });
  };

  return {
    getDevices,
    getDevice,
    getDeviceConfigurations,
    createConfiguration,
    getConfiguration,
    updateConfiguration,
  };
};
export type GetDevicesResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSmartHomeDeviceAPI>["getDevices"]>>
>;
export type GetDeviceResult = NonNullable<
  Awaited<ReturnType<ReturnType<typeof getSmartHomeDeviceAPI>["getDevice"]>>
>;
export type GetDeviceConfigurationsResult = NonNullable<
  Awaited<
    ReturnType<
      ReturnType<typeof getSmartHomeDeviceAPI>["getDeviceConfigurations"]
    >
  >
>;
export type CreateConfigurationResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSmartHomeDeviceAPI>["createConfiguration"]>
  >
>;
export type GetConfigurationResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSmartHomeDeviceAPI>["getConfiguration"]>
  >
>;
export type UpdateConfigurationResult = NonNullable<
  Awaited<
    ReturnType<ReturnType<typeof getSmartHomeDeviceAPI>["updateConfiguration"]>
  >
>;
