/**
 * Generated by orval v7.1.1 🍺
 * Do not edit manually.
 * Smart Home Device API
 * API to manage and retrieve smart home devices.
 * OpenAPI spec version: 1.0.0
 */
/**
 * Configuration data
 */
export type ConfigurationAllOfData = { [key: string]: unknown };

export type ConfigurationAllOf = {
  /** Configuration data */
  data: ConfigurationAllOfData;
};

export interface ConfigurationListItem {
  /** Whether the configuration is active or not */
  active: boolean;
  /** Unique identifier for the configuration */
  id: string;
  /** Human-readable name of the configuration */
  name: string;
}

export type Configuration = ConfigurationListItem & ConfigurationAllOf;

export interface Device {
  /** Unique identifier for the device */
  id: string;
  /** Human-readable name of the device */
  name: string;
  /** Current status of the device (e.g., on, off, idle) */
  status: string;
  /** Type of the smart device (e.g., light, thermostat) */
  type: string;
}
