// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/labstack/echo/v4"
	"github.com/max-weis/smarthome/device"
	"github.com/max-weis/smarthome/internal"
)

// Injectors from wire.go:

func Initialize() (*AppContext, error) {
	echo := internal.NewEchoServer()
	db, err := internal.NewDatabase()
	if err != nil {
		return nil, err
	}
	repository := device.NewRepository(db)
	serverInterface := device.NewHandler(echo, repository)
	appContext := &AppContext{
		echo:         echo,
		deviceServer: serverInterface,
	}
	return appContext, nil
}

// wire.go:

type AppContext struct {
	echo         *echo.Echo
	deviceServer device.ServerInterface
}
